
#if (((__CUDACC_VER_MAJOR__ == 11) && (__CUDACC_VER_MINOR__ >= 4)) || \
     (__CUDACC_VER_MAJOR__ > 11))
#define TVM_ENABLE_L2_PREFETCH 1
#else
#define TVM_ENABLE_L2_PREFETCH 0
#endif

#ifdef _WIN32
  using uint = unsigned int;
  using uchar = unsigned char;
  using ushort = unsigned short;
  using int64_t = long long;
  using uint64_t = unsigned long long;
#else
  #define uint unsigned int
  #define uchar unsigned char
  #define ushort unsigned short
  #define int64_t long long
  #define uint64_t unsigned long long
#endif
extern "C" __global__ void __launch_bounds__(112) conv2d_B1(float* __restrict__ data, float* __restrict__ kernel, float* __restrict__ conv2d_nhwc) {
  float conv2d_nhwc_local[4];
  __shared__ float pad_temp_shared[2320];
  __shared__ float kernel_shared[2304];
  // conv2d_nhwc_local[0] = 0.000000e+00f;
  // conv2d_nhwc_local[1] = 0.000000e+00f;
  // conv2d_nhwc_local[2] = 0.000000e+00f;
  // conv2d_nhwc_local[3] = 0.000000e+00f;
  // for (int rc_outer_outer = 0; rc_outer_outer < 4; ++rc_outer_outer) {
  //   __syncthreads();
  //   pad_temp_shared[((int)threadIdx.x)] = (((16 <= ((int)blockIdx.x)) && (1 <= ((((((int)blockIdx.x) & 15) >> 3) * 28) + (((int)threadIdx.x) >> 4)))) ? data[(((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((int)threadIdx.x) >> 4) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 3648)] : 0.000000e+00f);
  //   pad_temp_shared[(((int)threadIdx.x) + 112)] = ((16 <= ((int)blockIdx.x)) ? data[(((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((int)threadIdx.x) >> 4) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 3200)] : 0.000000e+00f);
  //   pad_temp_shared[(((int)threadIdx.x) + 224)] = ((16 <= ((int)blockIdx.x)) ? data[(((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((int)threadIdx.x) >> 4) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 2752)] : 0.000000e+00f);
  //   pad_temp_shared[(((int)threadIdx.x) + 336)] = ((16 <= ((int)blockIdx.x)) ? data[(((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((int)threadIdx.x) >> 4) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 2304)] : 0.000000e+00f);
  //   pad_temp_shared[(((int)threadIdx.x) + 448)] = (((1 <= (((((int)blockIdx.x) >> 4) * 4) + ((((int)threadIdx.x) + 448) / 464))) && (1 <= ((((((int)blockIdx.x) & 15) >> 3) * 28) + (((((int)threadIdx.x) >> 4) + 28) % 29)))) ? data[((((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)threadIdx.x) + 448) / 464) * 3584)) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((((int)threadIdx.x) >> 4) + 28) % 29) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 3648)] : 0.000000e+00f);
  //   pad_temp_shared[(((int)threadIdx.x) + 560)] = data[((((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)threadIdx.x) + 560) / 464) * 3584)) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((int)threadIdx.x) >> 4) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 3264)];
  //   pad_temp_shared[(((int)threadIdx.x) + 672)] = data[((((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)threadIdx.x) + 672) / 464) * 3584)) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((int)threadIdx.x) >> 4) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 2816)];
  //   pad_temp_shared[(((int)threadIdx.x) + 784)] = data[((((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)threadIdx.x) + 784) / 464) * 3584)) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((int)threadIdx.x) >> 4) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 2368)];
  //   pad_temp_shared[(((int)threadIdx.x) + 896)] = ((1 <= ((((((int)blockIdx.x) & 15) >> 3) * 28) + (((((int)threadIdx.x) >> 4) + 27) % 29))) ? data[((((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)threadIdx.x) + 896) / 464) * 3584)) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((((int)threadIdx.x) >> 4) + 27) % 29) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 3648)] : 0.000000e+00f);
  //   pad_temp_shared[(((int)threadIdx.x) + 1008)] = data[((((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)threadIdx.x) + 1008) / 464) * 3584)) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((int)threadIdx.x) >> 4) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 3328)];
  //   pad_temp_shared[(((int)threadIdx.x) + 1120)] = data[((((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)threadIdx.x) + 1120) / 464) * 3584)) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((int)threadIdx.x) >> 4) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 2880)];
  //   pad_temp_shared[(((int)threadIdx.x) + 1232)] = data[((((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)threadIdx.x) + 1232) / 464) * 3584)) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((int)threadIdx.x) >> 4) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 2432)];
  //   pad_temp_shared[(((int)threadIdx.x) + 1344)] = ((1 <= ((((((int)blockIdx.x) & 15) >> 3) * 28) + (((((int)threadIdx.x) >> 4) + 26) % 29))) ? data[((((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)threadIdx.x) + 1344) / 464) * 3584)) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((((int)threadIdx.x) >> 4) + 26) % 29) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 3648)] : 0.000000e+00f);
  //   pad_temp_shared[(((int)threadIdx.x) + 1456)] = data[((((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)threadIdx.x) + 1456) / 464) * 3584)) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((int)threadIdx.x) >> 4) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 3392)];
  //   pad_temp_shared[(((int)threadIdx.x) + 1568)] = data[((((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)threadIdx.x) + 1568) / 464) * 3584)) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((int)threadIdx.x) >> 4) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 2944)];
  //   pad_temp_shared[(((int)threadIdx.x) + 1680)] = data[((((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)threadIdx.x) + 1680) / 464) * 3584)) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((int)threadIdx.x) >> 4) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 2496)];
  //   pad_temp_shared[(((int)threadIdx.x) + 1792)] = ((1 <= ((((((int)blockIdx.x) & 15) >> 3) * 28) + (((((int)threadIdx.x) >> 4) + 25) % 29))) ? data[((((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)threadIdx.x) + 1792) / 464) * 3584)) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((((int)threadIdx.x) >> 4) + 25) % 29) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 3648)] : 0.000000e+00f);
  //   pad_temp_shared[(((int)threadIdx.x) + 1904)] = data[((((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)threadIdx.x) + 1904) / 464) * 3584)) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((int)threadIdx.x) >> 4) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 3456)];
  //   pad_temp_shared[(((int)threadIdx.x) + 2016)] = data[((((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)threadIdx.x) + 2016) / 464) * 3584)) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((int)threadIdx.x) >> 4) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 3008)];
  //   pad_temp_shared[(((int)threadIdx.x) + 2128)] = data[((((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)threadIdx.x) + 2128) / 464) * 3584)) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((int)threadIdx.x) >> 4) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 2560)];
  //   if (((int)threadIdx.x) < 80) {
  //     pad_temp_shared[(((int)threadIdx.x) + 2240)] = data[((((((((((int)blockIdx.x) >> 4) * 14336) + (((((int)threadIdx.x) + 2240) / 464) * 3584)) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((int)threadIdx.x) >> 4) * 64)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) - 2112)];
  //   }
  //   kernel_shared[((int)threadIdx.x)] = kernel[((((rc_outer_outer * 2048) + ((((int)threadIdx.x) >> 4) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15))];
  //   kernel_shared[(((int)threadIdx.x) + 112)] = kernel[(((((rc_outer_outer * 2048) + ((((int)threadIdx.x) >> 4) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15)) + 896)];
  //   kernel_shared[(((int)threadIdx.x) + 224)] = kernel[(((((((((int)threadIdx.x) + 224) >> 8) * 8192) + (rc_outer_outer * 2048)) + ((((((int)threadIdx.x) >> 4) + 14) & 15) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15))];
  //   kernel_shared[(((int)threadIdx.x) + 336)] = kernel[((((((((((int)threadIdx.x) + 336) >> 8) * 8192) + (rc_outer_outer * 2048)) + ((((int)threadIdx.x) >> 4) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15)) + 640)];
  //   kernel_shared[(((int)threadIdx.x) + 448)] = kernel[(((((((((int)threadIdx.x) + 448) >> 8) * 8192) + (rc_outer_outer * 2048)) + ((((((int)threadIdx.x) >> 4) + 12) & 15) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15))];
  //   kernel_shared[(((int)threadIdx.x) + 560)] = kernel[((((((((((int)threadIdx.x) + 560) >> 8) * 8192) + (rc_outer_outer * 2048)) + ((((int)threadIdx.x) >> 4) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15)) + 384)];
  //   kernel_shared[(((int)threadIdx.x) + 672)] = kernel[(((((((((int)threadIdx.x) + 672) >> 8) * 8192) + (rc_outer_outer * 2048)) + ((((((int)threadIdx.x) >> 4) + 10) & 15) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15))];
  //   kernel_shared[(((int)threadIdx.x) + 784)] = kernel[((((((((((int)threadIdx.x) + 784) >> 8) * 8192) + (rc_outer_outer * 2048)) + ((((int)threadIdx.x) >> 4) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15)) + 128)];
  //   kernel_shared[(((int)threadIdx.x) + 896)] = kernel[((((((((((int)threadIdx.x) + 896) >> 8) * 8192) + (rc_outer_outer * 2048)) + ((((int)threadIdx.x) >> 4) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15)) + 1024)];
  //   kernel_shared[(((int)threadIdx.x) + 1008)] = kernel[(((((((((int)threadIdx.x) + 1008) >> 8) * 8192) + (rc_outer_outer * 2048)) + ((((((int)threadIdx.x) >> 4) + 15) & 15) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15))];
  //   kernel_shared[(((int)threadIdx.x) + 1120)] = kernel[((((((((((int)threadIdx.x) + 1120) >> 8) * 8192) + (rc_outer_outer * 2048)) + ((((int)threadIdx.x) >> 4) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15)) + 768)];
  //   kernel_shared[(((int)threadIdx.x) + 1232)] = kernel[(((((((((int)threadIdx.x) + 1232) >> 8) * 8192) + (rc_outer_outer * 2048)) + ((((((int)threadIdx.x) >> 4) + 13) & 15) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15))];
  //   kernel_shared[(((int)threadIdx.x) + 1344)] = kernel[((((((((((int)threadIdx.x) + 1344) >> 8) * 8192) + (rc_outer_outer * 2048)) + ((((int)threadIdx.x) >> 4) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15)) + 512)];
  //   kernel_shared[(((int)threadIdx.x) + 1456)] = kernel[(((((((((int)threadIdx.x) + 1456) >> 8) * 8192) + (rc_outer_outer * 2048)) + ((((((int)threadIdx.x) >> 4) + 11) & 15) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15))];
  //   kernel_shared[(((int)threadIdx.x) + 1568)] = kernel[((((((((((int)threadIdx.x) + 1568) >> 8) * 8192) + (rc_outer_outer * 2048)) + ((((int)threadIdx.x) >> 4) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15)) + 256)];
  //   kernel_shared[(((int)threadIdx.x) + 1680)] = kernel[((((((((((int)threadIdx.x) + 1680) >> 8) * 8192) + (rc_outer_outer * 2048)) + ((((int)threadIdx.x) >> 4) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15)) + 1152)];
  //   kernel_shared[(((int)threadIdx.x) + 1792)] = kernel[(((((rc_outer_outer * 2048) + ((((int)threadIdx.x) >> 4) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15)) + 57344)];
  //   kernel_shared[(((int)threadIdx.x) + 1904)] = kernel[((((((((((int)threadIdx.x) + 1904) >> 8) * 8192) + (rc_outer_outer * 2048)) + ((((int)threadIdx.x) >> 4) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15)) + 896)];
  //   kernel_shared[(((int)threadIdx.x) + 2016)] = kernel[(((((((((int)threadIdx.x) + 2016) >> 8) * 8192) + (rc_outer_outer * 2048)) + ((((((int)threadIdx.x) >> 4) + 14) & 15) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15))];
  //   kernel_shared[(((int)threadIdx.x) + 2128)] = kernel[((((((((((int)threadIdx.x) + 2128) >> 8) * 8192) + (rc_outer_outer * 2048)) + ((((int)threadIdx.x) >> 4) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15)) + 640)];
  //   if (((int)threadIdx.x) < 64) {
  //     kernel_shared[(((int)threadIdx.x) + 2240)] = kernel[((((((((((int)threadIdx.x) + 2240) >> 8) * 8192) + (rc_outer_outer * 2048)) + ((((int)threadIdx.x) >> 4) * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15)) + 1536)];
  //   }
  //   __syncthreads();
  //   for (int rc_outer_inner = 0; rc_outer_inner < 4; ++rc_outer_inner) {
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[(((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4))] * kernel_shared[((rc_outer_inner * 64) + (((int)threadIdx.x) & 15))]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 16)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 2)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 32)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 3)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 48)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 16)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 256)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 17)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 272)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 18)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 288)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 19)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 304)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 32)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 512)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 33)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 528)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 34)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 544)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 35)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 560)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 464)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 768)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 465)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 784)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 466)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 800)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 467)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 816)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 480)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1024)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 481)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1040)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 482)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1056)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 483)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1072)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 496)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1280)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 497)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1296)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 498)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1312)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 499)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1328)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 928)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1536)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 929)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1552)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 930)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1568)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 931)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1584)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 944)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1792)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 945)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1808)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 946)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1824)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 947)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1840)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 960)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 2048)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 961)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 2064)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 962)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 2080)]));
  //     conv2d_nhwc_local[0] = (conv2d_nhwc_local[0] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 963)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 2096)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 32)] * kernel_shared[((rc_outer_inner * 64) + (((int)threadIdx.x) & 15))]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 33)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 16)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 34)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 32)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 35)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 48)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 48)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 256)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 49)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 272)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 50)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 288)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 51)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 304)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 64)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 512)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 65)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 528)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 66)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 544)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 67)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 560)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 496)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 768)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 497)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 784)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 498)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 800)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 499)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 816)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 512)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1024)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 513)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1040)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 514)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1056)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 515)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1072)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 528)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1280)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 529)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1296)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 530)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1312)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 531)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1328)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 960)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1536)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 961)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1552)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 962)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1568)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 963)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1584)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 976)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1792)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 977)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1808)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 978)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1824)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 979)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1840)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 992)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 2048)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 993)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 2064)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 994)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 2080)]));
  //     conv2d_nhwc_local[1] = (conv2d_nhwc_local[1] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 995)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 2096)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 928)] * kernel_shared[((rc_outer_inner * 64) + (((int)threadIdx.x) & 15))]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 929)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 16)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 930)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 32)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 931)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 48)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 944)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 256)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 945)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 272)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 946)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 288)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 947)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 304)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 960)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 512)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 961)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 528)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 962)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 544)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 963)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 560)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1392)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 768)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1393)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 784)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1394)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 800)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1395)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 816)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1408)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1024)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1409)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1040)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1410)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1056)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1411)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1072)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1424)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1280)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1425)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1296)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1426)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1312)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1427)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1328)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1856)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1536)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1857)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1552)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1858)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1568)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1859)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1584)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1872)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1792)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1873)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1808)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1874)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1824)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1875)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1840)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1888)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 2048)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1889)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 2064)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1890)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 2080)]));
  //     conv2d_nhwc_local[2] = (conv2d_nhwc_local[2] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1891)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 2096)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 960)] * kernel_shared[((rc_outer_inner * 64) + (((int)threadIdx.x) & 15))]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 961)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 16)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 962)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 32)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 963)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 48)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 976)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 256)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 977)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 272)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 978)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 288)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 979)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 304)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 992)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 512)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 993)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 528)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 994)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 544)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 995)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 560)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1424)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 768)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1425)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 784)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1426)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 800)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1427)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 816)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1440)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1024)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1441)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1040)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1442)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1056)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1443)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1072)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1456)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1280)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1457)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1296)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1458)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1312)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1459)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1328)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1888)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1536)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1889)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1552)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1890)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1568)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1891)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1584)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1904)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1792)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1905)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1808)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1906)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1824)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1907)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 1840)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1920)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 2048)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1921)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 2064)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1922)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 2080)]));
  //     conv2d_nhwc_local[3] = (conv2d_nhwc_local[3] + (pad_temp_shared[((((((int)threadIdx.x) >> 4) * 64) + (rc_outer_inner * 4)) + 1923)] * kernel_shared[(((rc_outer_inner * 64) + (((int)threadIdx.x) & 15)) + 2096)]));
  //   }
  // }
  // for (int yy_inner = 0; yy_inner < 2; ++yy_inner) {
  //   for (int xx_inner = 0; xx_inner < 2; ++xx_inner) {
  //     conv2d_nhwc[((((((((((int)blockIdx.x) >> 4) * 7168) + (yy_inner * 3584)) + (((((int)blockIdx.x) & 15) >> 3) * 1792)) + ((((int)threadIdx.x) >> 4) * 256)) + (xx_inner * 128)) + ((((int)blockIdx.x) & 7) * 16)) + (((int)threadIdx.x) & 15))] = conv2d_nhwc_local[((yy_inner * 2) + xx_inner)];
  //   }
  // }
}

extern "C" __global__ void __launch_bounds__(50) matmul_B16(float* __restrict__ data, float* __restrict__ weight, float* __restrict__ T_matmul_NT) {
  float T_matmul_NT_local[4];
  __shared__ float data_shared[256];
  __shared__ float weight_shared[3200];
  // T_matmul_NT_local[0] = 0.000000e+00f;
  // T_matmul_NT_local[1] = 0.000000e+00f;
  // T_matmul_NT_local[2] = 0.000000e+00f;
  // T_matmul_NT_local[3] = 0.000000e+00f;
  // for (int k_outer_outer = 0; k_outer_outer < 8; ++k_outer_outer) {
  //   __syncthreads();
  //   data_shared[(((int)threadIdx.x) * 4)] = data[(((((((int)blockIdx.x) / 20) * 2048) + ((((int)threadIdx.x) >> 4) * 512)) + (k_outer_outer * 64)) + ((((int)threadIdx.x) & 15) * 4))];
  //   data_shared[((((int)threadIdx.x) * 4) + 1)] = data[((((((((int)blockIdx.x) / 20) * 2048) + ((((int)threadIdx.x) >> 4) * 512)) + (k_outer_outer * 64)) + ((((int)threadIdx.x) & 15) * 4)) + 1)];
  //   data_shared[((((int)threadIdx.x) * 4) + 2)] = data[((((((((int)blockIdx.x) / 20) * 2048) + ((((int)threadIdx.x) >> 4) * 512)) + (k_outer_outer * 64)) + ((((int)threadIdx.x) & 15) * 4)) + 2)];
  //   data_shared[((((int)threadIdx.x) * 4) + 3)] = data[((((((((int)blockIdx.x) / 20) * 2048) + ((((int)threadIdx.x) >> 4) * 512)) + (k_outer_outer * 64)) + ((((int)threadIdx.x) & 15) * 4)) + 3)];
  //   if (((int)threadIdx.x) < 14) {
  //     data_shared[((((int)threadIdx.x) * 4) + 200)] = data[((((((((int)blockIdx.x) / 20) * 2048) + (((((int)threadIdx.x) + 50) >> 4) * 512)) + (k_outer_outer * 64)) + (((int)threadIdx.x) * 4)) + 8)];
  //   }
  //   if (((int)threadIdx.x) < 14) {
  //     data_shared[((((int)threadIdx.x) * 4) + 201)] = data[((((((((int)blockIdx.x) / 20) * 2048) + (((((int)threadIdx.x) + 50) >> 4) * 512)) + (k_outer_outer * 64)) + (((int)threadIdx.x) * 4)) + 9)];
  //   }
  //   if (((int)threadIdx.x) < 14) {
  //     data_shared[((((int)threadIdx.x) * 4) + 202)] = data[((((((((int)blockIdx.x) / 20) * 2048) + (((((int)threadIdx.x) + 50) >> 4) * 512)) + (k_outer_outer * 64)) + (((int)threadIdx.x) * 4)) + 10)];
  //   }
  //   if (((int)threadIdx.x) < 14) {
  //     data_shared[((((int)threadIdx.x) * 4) + 203)] = data[((((((((int)blockIdx.x) / 20) * 2048) + (((((int)threadIdx.x) + 50) >> 4) * 512)) + (k_outer_outer * 64)) + (((int)threadIdx.x) * 4)) + 11)];
  //   }
  //   *(float4*)(weight_shared + (((int)threadIdx.x) * 4)) = *(float4*)(weight + (((((((int)blockIdx.x) % 20) * 25600) + ((((int)threadIdx.x) >> 4) * 512)) + (k_outer_outer * 64)) + ((((int)threadIdx.x) & 15) * 4)));
  //   *(float4*)(weight_shared + ((((int)threadIdx.x) * 4) + 200)) = *(float4*)(weight + (((((((int)blockIdx.x) % 20) * 25600) + ((((((int)threadIdx.x) * 4) + 200) >> 6) * 512)) + (k_outer_outer * 64)) + (((((int)threadIdx.x) * 4) + 8) & 63)));
  //   *(float4*)(weight_shared + ((((int)threadIdx.x) * 4) + 400)) = *(float4*)(weight + (((((((int)blockIdx.x) % 20) * 25600) + ((((((int)threadIdx.x) * 4) + 400) >> 6) * 512)) + (k_outer_outer * 64)) + (((((int)threadIdx.x) * 4) + 16) & 63)));
  //   *(float4*)(weight_shared + ((((int)threadIdx.x) * 4) + 600)) = *(float4*)(weight + (((((((int)blockIdx.x) % 20) * 25600) + ((((((int)threadIdx.x) * 4) + 600) >> 6) * 512)) + (k_outer_outer * 64)) + (((((int)threadIdx.x) * 4) + 24) & 63)));
  //   *(float4*)(weight_shared + ((((int)threadIdx.x) * 4) + 800)) = *(float4*)(weight + (((((((int)blockIdx.x) % 20) * 25600) + ((((((int)threadIdx.x) * 4) + 800) >> 6) * 512)) + (k_outer_outer * 64)) + (((((int)threadIdx.x) * 4) + 32) & 63)));
  //   *(float4*)(weight_shared + ((((int)threadIdx.x) * 4) + 1000)) = *(float4*)(weight + (((((((int)blockIdx.x) % 20) * 25600) + ((((((int)threadIdx.x) * 4) + 1000) >> 6) * 512)) + (k_outer_outer * 64)) + (((((int)threadIdx.x) * 4) + 40) & 63)));
  //   *(float4*)(weight_shared + ((((int)threadIdx.x) * 4) + 1200)) = *(float4*)(weight + (((((((int)blockIdx.x) % 20) * 25600) + ((((((int)threadIdx.x) * 4) + 1200) >> 6) * 512)) + (k_outer_outer * 64)) + (((((int)threadIdx.x) * 4) + 48) & 63)));
  //   *(float4*)(weight_shared + ((((int)threadIdx.x) * 4) + 1400)) = *(float4*)(weight + (((((((int)blockIdx.x) % 20) * 25600) + ((((((int)threadIdx.x) * 4) + 1400) >> 6) * 512)) + (k_outer_outer * 64)) + (((((int)threadIdx.x) * 4) + 56) & 63)));
  //   *(float4*)(weight_shared + ((((int)threadIdx.x) * 4) + 1600)) = *(float4*)(weight + ((((((((int)blockIdx.x) % 20) * 25600) + ((((int)threadIdx.x) >> 4) * 512)) + (k_outer_outer * 64)) + ((((int)threadIdx.x) & 15) * 4)) + 12800));
  //   *(float4*)(weight_shared + ((((int)threadIdx.x) * 4) + 1800)) = *(float4*)(weight + (((((((int)blockIdx.x) % 20) * 25600) + ((((((int)threadIdx.x) * 4) + 1800) >> 6) * 512)) + (k_outer_outer * 64)) + (((((int)threadIdx.x) * 4) + 8) & 63)));
  //   *(float4*)(weight_shared + ((((int)threadIdx.x) * 4) + 2000)) = *(float4*)(weight + (((((((int)blockIdx.x) % 20) * 25600) + ((((((int)threadIdx.x) * 4) + 2000) >> 6) * 512)) + (k_outer_outer * 64)) + (((((int)threadIdx.x) * 4) + 16) & 63)));
  //   *(float4*)(weight_shared + ((((int)threadIdx.x) * 4) + 2200)) = *(float4*)(weight + (((((((int)blockIdx.x) % 20) * 25600) + ((((((int)threadIdx.x) * 4) + 2200) >> 6) * 512)) + (k_outer_outer * 64)) + (((((int)threadIdx.x) * 4) + 24) & 63)));
  //   *(float4*)(weight_shared + ((((int)threadIdx.x) * 4) + 2400)) = *(float4*)(weight + (((((((int)blockIdx.x) % 20) * 25600) + ((((((int)threadIdx.x) * 4) + 2400) >> 6) * 512)) + (k_outer_outer * 64)) + (((((int)threadIdx.x) * 4) + 32) & 63)));
  //   *(float4*)(weight_shared + ((((int)threadIdx.x) * 4) + 2600)) = *(float4*)(weight + (((((((int)blockIdx.x) % 20) * 25600) + ((((((int)threadIdx.x) * 4) + 2600) >> 6) * 512)) + (k_outer_outer * 64)) + (((((int)threadIdx.x) * 4) + 40) & 63)));
  //   *(float4*)(weight_shared + ((((int)threadIdx.x) * 4) + 2800)) = *(float4*)(weight + (((((((int)blockIdx.x) % 20) * 25600) + ((((((int)threadIdx.x) * 4) + 2800) >> 6) * 512)) + (k_outer_outer * 64)) + (((((int)threadIdx.x) * 4) + 48) & 63)));
  //   *(float4*)(weight_shared + ((((int)threadIdx.x) * 4) + 3000)) = *(float4*)(weight + (((((((int)blockIdx.x) % 20) * 25600) + ((((((int)threadIdx.x) * 4) + 3000) >> 6) * 512)) + (k_outer_outer * 64)) + (((((int)threadIdx.x) * 4) + 56) & 63)));
  //   __syncthreads();
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[0] * weight_shared[(((int)threadIdx.x) * 64)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[1] * weight_shared[((((int)threadIdx.x) * 64) + 1)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[2] * weight_shared[((((int)threadIdx.x) * 64) + 2)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[3] * weight_shared[((((int)threadIdx.x) * 64) + 3)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[4] * weight_shared[((((int)threadIdx.x) * 64) + 4)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[5] * weight_shared[((((int)threadIdx.x) * 64) + 5)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[6] * weight_shared[((((int)threadIdx.x) * 64) + 6)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[7] * weight_shared[((((int)threadIdx.x) * 64) + 7)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[8] * weight_shared[((((int)threadIdx.x) * 64) + 8)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[9] * weight_shared[((((int)threadIdx.x) * 64) + 9)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[10] * weight_shared[((((int)threadIdx.x) * 64) + 10)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[11] * weight_shared[((((int)threadIdx.x) * 64) + 11)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[12] * weight_shared[((((int)threadIdx.x) * 64) + 12)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[13] * weight_shared[((((int)threadIdx.x) * 64) + 13)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[14] * weight_shared[((((int)threadIdx.x) * 64) + 14)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[15] * weight_shared[((((int)threadIdx.x) * 64) + 15)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[64] * weight_shared[(((int)threadIdx.x) * 64)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[65] * weight_shared[((((int)threadIdx.x) * 64) + 1)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[66] * weight_shared[((((int)threadIdx.x) * 64) + 2)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[67] * weight_shared[((((int)threadIdx.x) * 64) + 3)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[68] * weight_shared[((((int)threadIdx.x) * 64) + 4)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[69] * weight_shared[((((int)threadIdx.x) * 64) + 5)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[70] * weight_shared[((((int)threadIdx.x) * 64) + 6)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[71] * weight_shared[((((int)threadIdx.x) * 64) + 7)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[72] * weight_shared[((((int)threadIdx.x) * 64) + 8)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[73] * weight_shared[((((int)threadIdx.x) * 64) + 9)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[74] * weight_shared[((((int)threadIdx.x) * 64) + 10)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[75] * weight_shared[((((int)threadIdx.x) * 64) + 11)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[76] * weight_shared[((((int)threadIdx.x) * 64) + 12)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[77] * weight_shared[((((int)threadIdx.x) * 64) + 13)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[78] * weight_shared[((((int)threadIdx.x) * 64) + 14)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[79] * weight_shared[((((int)threadIdx.x) * 64) + 15)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[128] * weight_shared[(((int)threadIdx.x) * 64)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[129] * weight_shared[((((int)threadIdx.x) * 64) + 1)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[130] * weight_shared[((((int)threadIdx.x) * 64) + 2)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[131] * weight_shared[((((int)threadIdx.x) * 64) + 3)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[132] * weight_shared[((((int)threadIdx.x) * 64) + 4)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[133] * weight_shared[((((int)threadIdx.x) * 64) + 5)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[134] * weight_shared[((((int)threadIdx.x) * 64) + 6)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[135] * weight_shared[((((int)threadIdx.x) * 64) + 7)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[136] * weight_shared[((((int)threadIdx.x) * 64) + 8)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[137] * weight_shared[((((int)threadIdx.x) * 64) + 9)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[138] * weight_shared[((((int)threadIdx.x) * 64) + 10)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[139] * weight_shared[((((int)threadIdx.x) * 64) + 11)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[140] * weight_shared[((((int)threadIdx.x) * 64) + 12)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[141] * weight_shared[((((int)threadIdx.x) * 64) + 13)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[142] * weight_shared[((((int)threadIdx.x) * 64) + 14)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[143] * weight_shared[((((int)threadIdx.x) * 64) + 15)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[192] * weight_shared[(((int)threadIdx.x) * 64)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[193] * weight_shared[((((int)threadIdx.x) * 64) + 1)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[194] * weight_shared[((((int)threadIdx.x) * 64) + 2)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[195] * weight_shared[((((int)threadIdx.x) * 64) + 3)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[196] * weight_shared[((((int)threadIdx.x) * 64) + 4)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[197] * weight_shared[((((int)threadIdx.x) * 64) + 5)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[198] * weight_shared[((((int)threadIdx.x) * 64) + 6)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[199] * weight_shared[((((int)threadIdx.x) * 64) + 7)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[200] * weight_shared[((((int)threadIdx.x) * 64) + 8)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[201] * weight_shared[((((int)threadIdx.x) * 64) + 9)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[202] * weight_shared[((((int)threadIdx.x) * 64) + 10)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[203] * weight_shared[((((int)threadIdx.x) * 64) + 11)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[204] * weight_shared[((((int)threadIdx.x) * 64) + 12)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[205] * weight_shared[((((int)threadIdx.x) * 64) + 13)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[206] * weight_shared[((((int)threadIdx.x) * 64) + 14)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[207] * weight_shared[((((int)threadIdx.x) * 64) + 15)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[16] * weight_shared[((((int)threadIdx.x) * 64) + 16)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[17] * weight_shared[((((int)threadIdx.x) * 64) + 17)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[18] * weight_shared[((((int)threadIdx.x) * 64) + 18)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[19] * weight_shared[((((int)threadIdx.x) * 64) + 19)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[20] * weight_shared[((((int)threadIdx.x) * 64) + 20)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[21] * weight_shared[((((int)threadIdx.x) * 64) + 21)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[22] * weight_shared[((((int)threadIdx.x) * 64) + 22)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[23] * weight_shared[((((int)threadIdx.x) * 64) + 23)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[24] * weight_shared[((((int)threadIdx.x) * 64) + 24)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[25] * weight_shared[((((int)threadIdx.x) * 64) + 25)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[26] * weight_shared[((((int)threadIdx.x) * 64) + 26)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[27] * weight_shared[((((int)threadIdx.x) * 64) + 27)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[28] * weight_shared[((((int)threadIdx.x) * 64) + 28)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[29] * weight_shared[((((int)threadIdx.x) * 64) + 29)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[30] * weight_shared[((((int)threadIdx.x) * 64) + 30)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[31] * weight_shared[((((int)threadIdx.x) * 64) + 31)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[80] * weight_shared[((((int)threadIdx.x) * 64) + 16)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[81] * weight_shared[((((int)threadIdx.x) * 64) + 17)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[82] * weight_shared[((((int)threadIdx.x) * 64) + 18)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[83] * weight_shared[((((int)threadIdx.x) * 64) + 19)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[84] * weight_shared[((((int)threadIdx.x) * 64) + 20)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[85] * weight_shared[((((int)threadIdx.x) * 64) + 21)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[86] * weight_shared[((((int)threadIdx.x) * 64) + 22)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[87] * weight_shared[((((int)threadIdx.x) * 64) + 23)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[88] * weight_shared[((((int)threadIdx.x) * 64) + 24)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[89] * weight_shared[((((int)threadIdx.x) * 64) + 25)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[90] * weight_shared[((((int)threadIdx.x) * 64) + 26)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[91] * weight_shared[((((int)threadIdx.x) * 64) + 27)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[92] * weight_shared[((((int)threadIdx.x) * 64) + 28)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[93] * weight_shared[((((int)threadIdx.x) * 64) + 29)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[94] * weight_shared[((((int)threadIdx.x) * 64) + 30)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[95] * weight_shared[((((int)threadIdx.x) * 64) + 31)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[144] * weight_shared[((((int)threadIdx.x) * 64) + 16)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[145] * weight_shared[((((int)threadIdx.x) * 64) + 17)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[146] * weight_shared[((((int)threadIdx.x) * 64) + 18)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[147] * weight_shared[((((int)threadIdx.x) * 64) + 19)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[148] * weight_shared[((((int)threadIdx.x) * 64) + 20)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[149] * weight_shared[((((int)threadIdx.x) * 64) + 21)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[150] * weight_shared[((((int)threadIdx.x) * 64) + 22)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[151] * weight_shared[((((int)threadIdx.x) * 64) + 23)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[152] * weight_shared[((((int)threadIdx.x) * 64) + 24)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[153] * weight_shared[((((int)threadIdx.x) * 64) + 25)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[154] * weight_shared[((((int)threadIdx.x) * 64) + 26)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[155] * weight_shared[((((int)threadIdx.x) * 64) + 27)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[156] * weight_shared[((((int)threadIdx.x) * 64) + 28)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[157] * weight_shared[((((int)threadIdx.x) * 64) + 29)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[158] * weight_shared[((((int)threadIdx.x) * 64) + 30)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[159] * weight_shared[((((int)threadIdx.x) * 64) + 31)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[208] * weight_shared[((((int)threadIdx.x) * 64) + 16)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[209] * weight_shared[((((int)threadIdx.x) * 64) + 17)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[210] * weight_shared[((((int)threadIdx.x) * 64) + 18)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[211] * weight_shared[((((int)threadIdx.x) * 64) + 19)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[212] * weight_shared[((((int)threadIdx.x) * 64) + 20)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[213] * weight_shared[((((int)threadIdx.x) * 64) + 21)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[214] * weight_shared[((((int)threadIdx.x) * 64) + 22)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[215] * weight_shared[((((int)threadIdx.x) * 64) + 23)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[216] * weight_shared[((((int)threadIdx.x) * 64) + 24)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[217] * weight_shared[((((int)threadIdx.x) * 64) + 25)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[218] * weight_shared[((((int)threadIdx.x) * 64) + 26)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[219] * weight_shared[((((int)threadIdx.x) * 64) + 27)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[220] * weight_shared[((((int)threadIdx.x) * 64) + 28)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[221] * weight_shared[((((int)threadIdx.x) * 64) + 29)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[222] * weight_shared[((((int)threadIdx.x) * 64) + 30)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[223] * weight_shared[((((int)threadIdx.x) * 64) + 31)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[32] * weight_shared[((((int)threadIdx.x) * 64) + 32)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[33] * weight_shared[((((int)threadIdx.x) * 64) + 33)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[34] * weight_shared[((((int)threadIdx.x) * 64) + 34)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[35] * weight_shared[((((int)threadIdx.x) * 64) + 35)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[36] * weight_shared[((((int)threadIdx.x) * 64) + 36)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[37] * weight_shared[((((int)threadIdx.x) * 64) + 37)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[38] * weight_shared[((((int)threadIdx.x) * 64) + 38)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[39] * weight_shared[((((int)threadIdx.x) * 64) + 39)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[40] * weight_shared[((((int)threadIdx.x) * 64) + 40)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[41] * weight_shared[((((int)threadIdx.x) * 64) + 41)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[42] * weight_shared[((((int)threadIdx.x) * 64) + 42)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[43] * weight_shared[((((int)threadIdx.x) * 64) + 43)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[44] * weight_shared[((((int)threadIdx.x) * 64) + 44)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[45] * weight_shared[((((int)threadIdx.x) * 64) + 45)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[46] * weight_shared[((((int)threadIdx.x) * 64) + 46)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[47] * weight_shared[((((int)threadIdx.x) * 64) + 47)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[96] * weight_shared[((((int)threadIdx.x) * 64) + 32)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[97] * weight_shared[((((int)threadIdx.x) * 64) + 33)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[98] * weight_shared[((((int)threadIdx.x) * 64) + 34)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[99] * weight_shared[((((int)threadIdx.x) * 64) + 35)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[100] * weight_shared[((((int)threadIdx.x) * 64) + 36)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[101] * weight_shared[((((int)threadIdx.x) * 64) + 37)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[102] * weight_shared[((((int)threadIdx.x) * 64) + 38)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[103] * weight_shared[((((int)threadIdx.x) * 64) + 39)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[104] * weight_shared[((((int)threadIdx.x) * 64) + 40)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[105] * weight_shared[((((int)threadIdx.x) * 64) + 41)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[106] * weight_shared[((((int)threadIdx.x) * 64) + 42)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[107] * weight_shared[((((int)threadIdx.x) * 64) + 43)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[108] * weight_shared[((((int)threadIdx.x) * 64) + 44)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[109] * weight_shared[((((int)threadIdx.x) * 64) + 45)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[110] * weight_shared[((((int)threadIdx.x) * 64) + 46)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[111] * weight_shared[((((int)threadIdx.x) * 64) + 47)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[160] * weight_shared[((((int)threadIdx.x) * 64) + 32)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[161] * weight_shared[((((int)threadIdx.x) * 64) + 33)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[162] * weight_shared[((((int)threadIdx.x) * 64) + 34)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[163] * weight_shared[((((int)threadIdx.x) * 64) + 35)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[164] * weight_shared[((((int)threadIdx.x) * 64) + 36)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[165] * weight_shared[((((int)threadIdx.x) * 64) + 37)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[166] * weight_shared[((((int)threadIdx.x) * 64) + 38)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[167] * weight_shared[((((int)threadIdx.x) * 64) + 39)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[168] * weight_shared[((((int)threadIdx.x) * 64) + 40)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[169] * weight_shared[((((int)threadIdx.x) * 64) + 41)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[170] * weight_shared[((((int)threadIdx.x) * 64) + 42)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[171] * weight_shared[((((int)threadIdx.x) * 64) + 43)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[172] * weight_shared[((((int)threadIdx.x) * 64) + 44)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[173] * weight_shared[((((int)threadIdx.x) * 64) + 45)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[174] * weight_shared[((((int)threadIdx.x) * 64) + 46)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[175] * weight_shared[((((int)threadIdx.x) * 64) + 47)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[224] * weight_shared[((((int)threadIdx.x) * 64) + 32)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[225] * weight_shared[((((int)threadIdx.x) * 64) + 33)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[226] * weight_shared[((((int)threadIdx.x) * 64) + 34)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[227] * weight_shared[((((int)threadIdx.x) * 64) + 35)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[228] * weight_shared[((((int)threadIdx.x) * 64) + 36)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[229] * weight_shared[((((int)threadIdx.x) * 64) + 37)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[230] * weight_shared[((((int)threadIdx.x) * 64) + 38)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[231] * weight_shared[((((int)threadIdx.x) * 64) + 39)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[232] * weight_shared[((((int)threadIdx.x) * 64) + 40)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[233] * weight_shared[((((int)threadIdx.x) * 64) + 41)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[234] * weight_shared[((((int)threadIdx.x) * 64) + 42)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[235] * weight_shared[((((int)threadIdx.x) * 64) + 43)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[236] * weight_shared[((((int)threadIdx.x) * 64) + 44)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[237] * weight_shared[((((int)threadIdx.x) * 64) + 45)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[238] * weight_shared[((((int)threadIdx.x) * 64) + 46)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[239] * weight_shared[((((int)threadIdx.x) * 64) + 47)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[48] * weight_shared[((((int)threadIdx.x) * 64) + 48)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[49] * weight_shared[((((int)threadIdx.x) * 64) + 49)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[50] * weight_shared[((((int)threadIdx.x) * 64) + 50)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[51] * weight_shared[((((int)threadIdx.x) * 64) + 51)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[52] * weight_shared[((((int)threadIdx.x) * 64) + 52)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[53] * weight_shared[((((int)threadIdx.x) * 64) + 53)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[54] * weight_shared[((((int)threadIdx.x) * 64) + 54)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[55] * weight_shared[((((int)threadIdx.x) * 64) + 55)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[56] * weight_shared[((((int)threadIdx.x) * 64) + 56)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[57] * weight_shared[((((int)threadIdx.x) * 64) + 57)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[58] * weight_shared[((((int)threadIdx.x) * 64) + 58)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[59] * weight_shared[((((int)threadIdx.x) * 64) + 59)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[60] * weight_shared[((((int)threadIdx.x) * 64) + 60)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[61] * weight_shared[((((int)threadIdx.x) * 64) + 61)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[62] * weight_shared[((((int)threadIdx.x) * 64) + 62)]));
  //   T_matmul_NT_local[0] = (T_matmul_NT_local[0] + (data_shared[63] * weight_shared[((((int)threadIdx.x) * 64) + 63)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[112] * weight_shared[((((int)threadIdx.x) * 64) + 48)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[113] * weight_shared[((((int)threadIdx.x) * 64) + 49)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[114] * weight_shared[((((int)threadIdx.x) * 64) + 50)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[115] * weight_shared[((((int)threadIdx.x) * 64) + 51)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[116] * weight_shared[((((int)threadIdx.x) * 64) + 52)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[117] * weight_shared[((((int)threadIdx.x) * 64) + 53)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[118] * weight_shared[((((int)threadIdx.x) * 64) + 54)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[119] * weight_shared[((((int)threadIdx.x) * 64) + 55)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[120] * weight_shared[((((int)threadIdx.x) * 64) + 56)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[121] * weight_shared[((((int)threadIdx.x) * 64) + 57)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[122] * weight_shared[((((int)threadIdx.x) * 64) + 58)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[123] * weight_shared[((((int)threadIdx.x) * 64) + 59)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[124] * weight_shared[((((int)threadIdx.x) * 64) + 60)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[125] * weight_shared[((((int)threadIdx.x) * 64) + 61)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[126] * weight_shared[((((int)threadIdx.x) * 64) + 62)]));
  //   T_matmul_NT_local[1] = (T_matmul_NT_local[1] + (data_shared[127] * weight_shared[((((int)threadIdx.x) * 64) + 63)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[176] * weight_shared[((((int)threadIdx.x) * 64) + 48)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[177] * weight_shared[((((int)threadIdx.x) * 64) + 49)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[178] * weight_shared[((((int)threadIdx.x) * 64) + 50)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[179] * weight_shared[((((int)threadIdx.x) * 64) + 51)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[180] * weight_shared[((((int)threadIdx.x) * 64) + 52)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[181] * weight_shared[((((int)threadIdx.x) * 64) + 53)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[182] * weight_shared[((((int)threadIdx.x) * 64) + 54)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[183] * weight_shared[((((int)threadIdx.x) * 64) + 55)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[184] * weight_shared[((((int)threadIdx.x) * 64) + 56)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[185] * weight_shared[((((int)threadIdx.x) * 64) + 57)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[186] * weight_shared[((((int)threadIdx.x) * 64) + 58)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[187] * weight_shared[((((int)threadIdx.x) * 64) + 59)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[188] * weight_shared[((((int)threadIdx.x) * 64) + 60)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[189] * weight_shared[((((int)threadIdx.x) * 64) + 61)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[190] * weight_shared[((((int)threadIdx.x) * 64) + 62)]));
  //   T_matmul_NT_local[2] = (T_matmul_NT_local[2] + (data_shared[191] * weight_shared[((((int)threadIdx.x) * 64) + 63)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[240] * weight_shared[((((int)threadIdx.x) * 64) + 48)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[241] * weight_shared[((((int)threadIdx.x) * 64) + 49)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[242] * weight_shared[((((int)threadIdx.x) * 64) + 50)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[243] * weight_shared[((((int)threadIdx.x) * 64) + 51)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[244] * weight_shared[((((int)threadIdx.x) * 64) + 52)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[245] * weight_shared[((((int)threadIdx.x) * 64) + 53)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[246] * weight_shared[((((int)threadIdx.x) * 64) + 54)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[247] * weight_shared[((((int)threadIdx.x) * 64) + 55)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[248] * weight_shared[((((int)threadIdx.x) * 64) + 56)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[249] * weight_shared[((((int)threadIdx.x) * 64) + 57)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[250] * weight_shared[((((int)threadIdx.x) * 64) + 58)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[251] * weight_shared[((((int)threadIdx.x) * 64) + 59)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[252] * weight_shared[((((int)threadIdx.x) * 64) + 60)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[253] * weight_shared[((((int)threadIdx.x) * 64) + 61)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[254] * weight_shared[((((int)threadIdx.x) * 64) + 62)]));
  //   T_matmul_NT_local[3] = (T_matmul_NT_local[3] + (data_shared[255] * weight_shared[((((int)threadIdx.x) * 64) + 63)]));
  // }
  // for (int i_inner = 0; i_inner < 4; ++i_inner) {
  //   T_matmul_NT[(((((((int)blockIdx.x) / 20) * 4000) + (i_inner * 1000)) + ((((int)blockIdx.x) % 20) * 50)) + ((int)threadIdx.x))] = T_matmul_NT_local[i_inner];
  // }
}