FusionSet:
- Set:
  - bgemm_0
- Set:
  - conv2d_0
KernelInfo:
  bgemm_0:
  - 16
  - 512
  - 64
  - 512
  bgemm_1:
  - 16
  - 512
  - 512
  - 64
  bgemm_2:
  - 16
  - 256
  - 80
  - 256
  bgemm_3:
  - 16
  - 256
  - 256
  - 80
  bgemm_4:
  - 16
  - 208
  - 80
  - 208
  bgemm_5:
  - 16
  - 208
  - 208
  - 80
  bgemm_6:
  - 1
  - 1024
  - 64
  - 512
  bgemm_7:
  - 1
  - 1024
  - 512
  - 64
  conv2d_0:
  - 1
  - 112
  - 112
  - 192
  - 64
  - 3
  - 3
  - 2
  - 0
  conv2d_1:
  - 1
  - 147
  - 147
  - 64
  - 32
  - 3
  - 3
  - 2
  - 0
  conv2d_2:
  - 1
  - 56
  - 56
  - 128
  - 64
  - 3
  - 3
  - 1
  - 0
  conv2d_3:
  - 1
  - 28
  - 28
  - 256
  - 128
  - 3
  - 3
  - 1
  - 0
  conv2d_4:
  - 1
  - 227
  - 227
  - 64
  - 16
  - 3
  - 3
  - 4
  - 0
  conv2d_5:
  - 1
  - 56
  - 56
  - 64
  - 64
  - 1
  - 1
  - 1
  - 0
  conv2d_6:
  - 1
  - 56
  - 56
  - 64
  - 64
  - 1
  - 1
  - 1
  - 0
  conv2d_7:
  - 1
  - 56
  - 56
  - 256
  - 256
  - 1
  - 1
  - 1
  - 0
