FusionSet:
  - Set:
    - bgemm_0
    - bgemm_1
    - bgemm_2
    - bgemm_3
    - bgemm_4
    - bgemm_5
    - bgemm_6
    - bgemm_7
  - Set:
    - conv2d_0
    - conv2d_1
    - conv2d_2
    - conv2d_3
    - conv2d_4
    - conv2d_5
    - conv2d_6
    - conv2d_7
KernelInfo:
  bgemm_0:
    - 256 # batch_size
    - 512 # M
    - 64  # K
    - 512 # N
  bgemm_1:
    - 256
    - 512
    - 512
    - 64
  bgemm_2:
    - 256
    - 256
    - 80
    - 256
  bgemm_3:
    - 256
    - 256
    - 256
    - 80
  bgemm_4:
    - 256
    - 208
    - 80
    - 208
  bgemm_5:
    - 256
    - 208
    - 208
    - 80
  bgemm_6:
    - 256
    - 1024
    - 64
    - 512
  bgemm_7:
    - 256
    - 1024
    - 512
    - 64
  conv2d_0:
    - 256 # N
    - 112 # H
    - 112 # W
    - 192 # CO
    - 64  # CI
    - 3   # KH
    - 3   # KW
    - 2   # stride
    - 0   # padding
  conv2d_1:
    - 256
    - 147
    - 147
    - 64
    - 32
    - 3
    - 3
    - 2
    - 0
  conv2d_2:
    - 256
    - 56
    - 56
    - 128
    - 64
    - 3
    - 3
    - 1
    - 0
  conv2d_3:
    - 256
    - 28
    - 28
    - 256
    - 128
    - 3
    - 3
    - 1
    - 0
  conv2d_4:
    - 256
    - 227
    - 227
    - 64
    - 16
    - 3
    - 3
    - 4
    - 0
  conv2d_5:
    - 256
    - 56
    - 56
    - 64
    - 64
    - 1
    - 1
    - 1
    - 0
  conv2d_6:
    - 256
    - 56
    - 56
    - 64
    - 64
    - 1
    - 1
    - 1
    - 0
  conv2d_7:
    - 256
    - 56
    - 56
    - 256
    - 256
    - 1
    - 1
    - 1
    - 0