FusionSet:
  - Set:
    - bgemm_0
    - bgemm_1
    - bgemm_2
    - bgemm_3
    - bgemm_4
    - bgemm_5
    - bgemm_6
    - bgemm_7
    - bgemm_8
    - bgemm_9
    - bgemm_10
    - bgemm_11
    - bgemm_12
    - bgemm_13
    - bgemm_14
    - bgemm_15
  - Set:
    - conv2d_0
    - conv2d_1
    - conv2d_2
    - conv2d_3
    - conv2d_4
    - conv2d_5
    - conv2d_6
    - conv2d_7
    - conv2d_8
    - conv2d_9
    - conv2d_10
    - conv2d_11
    - conv2d_12
    - conv2d_13
KernelInfo:
  bgemm_0:
    - 128 # batch_size
    - 512 # M
    - 64  # K
    - 512 # N
  bgemm_1:
    - 128
    - 512
    - 512
    - 64
  bgemm_2:
    - 512
    - 256
    - 64
    - 256
  bgemm_3:
    - 512
    - 256
    - 256
    - 64
  bgemm_4:
    - 512
    - 256
    - 80
    - 256
  bgemm_5:
    - 512
    - 256
    - 256
    - 80
  bgemm_6:
    - 512
    - 208
    - 64
    - 208
  bgemm_7:
    - 256
    - 208
    - 208
    - 64
  bgemm_8:
    - 512
    - 208
    - 80
    - 208
  bgemm_9:
    - 512
    - 208
    - 208
    - 80
  bgemm_10:
    - 256
    - 512
    - 64
    - 256
  bgemm_11:
    - 256
    - 512
    - 256
    - 64
  bgemm_12:
    - 128
    - 768
    - 64
    - 384
  bgemm_13:
    - 128
    - 768
    - 384
    - 64
  bgemm_14:
    - 64
    - 1024
    - 64
    - 512
  bgemm_15:
    - 64
    - 1024
    - 512
    - 64
  conv2d_0:
    - 2   # N
    - 112 # H
    - 112 # W
    - 192 # CO
    - 64  # CI
    - 3   # KH
    - 3   # KW
    - 2   # stride
    - 0   # padding
  conv2d_1:
    - 64
    - 55
    - 55
    - 128
    - 192
    - 1
    - 1
    - 1
    - 0
  conv2d_2:
    - 1
    - 147
    - 147
    - 64
    - 32
    - 3
    - 3
    - 2
    - 0
  conv2d_3:
    - 4
    - 73
    - 73
    - 80
    - 64
    - 1
    - 1
    - 1
    - 0
  conv2d_4:
    - 32
    - 56
    - 56
    - 128
    - 64
    - 3
    - 3
    - 1
    - 0
  conv2d_5:
    - 128
    - 54
    - 54
    - 64
    - 128
    - 1
    - 1
    - 1
    - 0
  conv2d_6:
    - 16
    - 28
    - 28
    - 256
    - 128
    - 3
    - 3
    - 1
    - 0
  conv2d_7:
    - 128
    - 26
    - 26
    - 128
    - 256
    - 1
    - 1
    - 1
    - 0
  conv2d_8:
    - 64
    - 227
    - 227
    - 64
    - 16
    - 3
    - 3
    - 4
    - 0
  conv2d_9:
    - 512
    - 57
    - 57
    - 16
    - 64
    - 1
    - 1
    - 1
    - 0
  conv2d_10:
    - 512
    - 56
    - 56
    - 64
    - 64
    - 1
    - 1
    - 1
    - 0
  conv2d_11:
    - 64
    - 56
    - 56
    - 64
    - 64
    - 3
    - 3
    - 1
    - 0
  conv2d_12:
    - 32
    - 56
    - 56
    - 256
    - 256
    - 1
    - 1
    - 1
    - 0
  conv2d_13:
    - 128
    - 56
    - 56
    - 64
    - 256
    - 1
    - 1
    - 1
    - 0